"""Payment Table Added

Revision ID: 34348cc003fe
Revises: 6584fc53474a
Create Date: 2024-04-11 05:32:42.129165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34348cc003fe'
down_revision = '6584fc53474a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('payment_number', sa.String(length=40), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('gold_gain', sa.Float(), nullable=True),
    sa.Column('date_of_payment', sa.Date(), nullable=True),
    sa.Column('no_of_notification_sent', sa.Integer(), nullable=True),
    sa.Column('is_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notified_date', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=30), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_payment_number'), 'payment', ['payment_number'], unique=True)
    op.add_column('client', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('client', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'is_active')
    op.drop_column('client', 'is_delete')
    op.drop_index(op.f('ix_payment_payment_number'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
